name: CInew

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, local-runner]  # Adjust to your runner label if needed

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up cache for Verilator
      id: cache-verilator
      uses: actions/cache@v3
      with:
        path: /home/runner/verilator
        key: verilator-cache-${{ runner.os }}-${{ hashFiles('**/verilator') }}
        restore-keys: |
          verilator-cache-${{ runner.os }}-

    - name: Install Verilator if not cached
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      run: |
        mkdir -p /home/runner/verilator
        wget https://example.com/verilator.tar.gz -O /home/runner/verilator/verilator.tar.gz
        tar -xzf /home/runner/verilator/verilator.tar.gz -C /home/runner/verilator
        export PATH=/home/runner/verilator/bin:$PATH

    - name: Trigger Local Script
      run: |
        echo "Triggering the local CI script..."
        bash ./scripts/run_ci.sh
